* types & grammar
  1. 判断以下结果
     #+BEGIN_SRC javascript
     var s = 'abc';
     s[1] = 'B';
     console.log(s);
   输出：abc

     var l = new String('abc');
     l[1] = 'B';
     console.log(l);
    输出：{
        0:"a"
        1:"b"
        2:"c"
     }
     #+END_SRC

  2. 如何逆序一个字符串？
     可将字符串转化为数组后用数组的方法reverse，str.split('').reverse()

  3. 接上，为什么不能直接使用
     #+BEGIN_SRC javascript
     Array.prototype.reverse.call(str)
     #+END_SRC
     逆序字符串？
字符串没有reverse方法，要将其转为数组

  4. 判断以下结果，为什么会出现这样的情况，如何做出正确的比较？
     #+BEGIN_SRC javascript
     0.1 + 0.2 === 0.3;
     0.8 - 0.6 === 0.3;
     #+END_SRC

  5. 如何判断一个数值为整数？
可将该数值做向上取整或向下取整，在与原值做===比较

  6. 如何判断一个数值为+0？
可用正则表达式以0结束

  7. 以下代码中'abc'作为primitive value, 如何访问toUpperCase 方法?
     #+BEGIN_SRC javascript
     'abc'.toUpperCase();
     #+END_SRC

  8. 判断以下结果
     #+BEGIN_SRC javascript
     Array.isArray(Array.prototype);
     #+END_SRC

  9. 判断以下结果
     #+BEGIN_SRC javascript
     Boolean(Boolean(false));
     Boolean(document.all);

     [] == '';
     [3] == 3;
     [] == false;
     42 == true;
     #+END_SRC

  10. 找出以下代码问题(TDZ)
      #+BEGIN_SRC javascript
      var a = 3;
      let a;
      #+END_SRC
在es6中，使用let声明变量只能被声明一次

  11. 找出以下代码问题(TDZ)
      #+BEGIN_SRC javascript
      var b = 3;
      function foo(a = 42, b = a + b + 5) {
        // ..
      }

      foo();
      #+END_SRC

* scope & closures

  1. var a = 2 中, Engine, Scope, Compiler 做了什么工作?

  2. 判断以下结果(lexical scope)
     #+BEGIN_SRC javascript
     var scope = 'global scope';
     function checkscope() {
         var scope = 'local scope';
         function f() {
           return scope;
         }
         return f;
     }
     #+END_SRC

  3. 判断以下结果(Hoisting)
     #+BEGIN_SRC javascript
     console.log(a);
     var a = 3;
     #+END_SRC
输出：undefined

  4. 判断以下结果(Function First)
     #+BEGIN_SRC javascript
     var foo = 1;
     function foo() {}
     console.log(foo);
     #+END_SRC
输出：1

  5. 判断以下结果(IIFE & Function First)
     #+BEGIN_SRC javascript
     var foo = 1;
     (function () {
       foo = 2;
       function foo (){
       }
       console.log(foo);
     })()
     console.log(foo);
     #+END_SRC
输出：2  1

  6. 判断以下结果，如何按序输出(Closure)
     #+BEGIN_SRC javascript
     for (var i = 0; i < 10; i++) {
       setTimeout(function () {
         console.log(i);
       }, i * 1000);
     }
     #+END_SRC
输出：十个10

* this & object prototypes
  1. 判断以下结果(Default Binding)
     #+BEGIN_SRC javascript
     function foo() {
       "use strict"
       console.log(this.a);
     }
     var a = 2;

     foo();
     #+END_SRC

严格模式下，未声明的变量会报错
  2. 判断以下结果
     #+BEGIN_SRC javascript
     "use strict"
     var a = 2;
     console.log(this);
     #+END_SRC
全局作用域下，this指向window

  3. 判断以下结果(strict mode & default binding)
     #+BEGIN_SRC javascript
     function foo() {
       console.log(this.a);
     }
     var a = 2;
     (function(){
       "use strict"
       foo();
     })();
     #+END_SRC
严格模式下，未声明的变量会报错

  4. 判断以下结果(hard binding)
     #+BEGIN_SRC javascript
     function foo() {
       console.log(this.a);
     }
     const o1 = { a: 3 };
     const o2 = { a: 4 };

     foo.bind(o1).bind(o2)();
     #+END_SRC
输出：3
  5. 如何实现
     #+BEGIN_SRC javascript
     Function.prototype.bind
     Function.prototype.softBind
     #+END_SRC

  6. new 的过程中发生了什么, 判断以下结果(new)
     #+BEGIN_SRC javascript
     function F() {
       this.a = 3;
       return {
         a: 4
       }
     }
     const f = new F();
     console.log(f.a);
     #+END_SRC
     new执行过程：
         1，创建一个新的对象
         2，将构造函数的执行对象赋值
         3，执行构造函数中的代码
         4， 返回新生成的对象实例
         this的指向为最终的返回值
     输出：4
  7. 什么是data descriptor 和 accessor descriptor?

  8. 如何访问一个对象的属性与如何对一个对象的属性赋值(Get & Put)?
      可以使用“ . ”和“ [ ] ”来访问对象的属性。
      获取到属性后可用等号赋值
  9. 如何遍历一个对象(iterator)?
      1、for 循环遍历
      2、JavaScript 提供了 foreach(可遍历 Array对象
      Array.forEach(function(value , index , array){ })
      3、for...in来枚举获得

  10. 如何实现一个继承(Object.create & call)?
  可利用call或者apply来实现继承
      var obj = new Object();
      sayColor.call(obj, 参数);

  11. 如何实现 __proto__?
      function Foo(){}
      Foo.prototype = Boo;
      var f = new Foo();
      f.__proto__ === Foo.prototype
  12. 如何实现Object.create?
      const person = {
      name: "li",
      printname: function () {
         console.log(this.name);
      }
      };
      const me = Object.create(person);
      me.name = "TL";
      me.printname();
